### ISSUE TITLE
Errors during 'make'

### ISSUE THREAD

**Issue by maritsas** [lwfinger/rtl8192ee#10]
Hi,

I have the Wireless PCI Express adapter installed -> TL-WN881ND:

> root@luffy:~/rtl8192ee# lspci | grep -i --color wireless
01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter

and I noticed that while trying to install the driver from your repository I am getting the following errors:

`/root/rtl8192ee/core/rtw_recv.c: In function ‘rtw_signal_stat_timer_hdl’:
/root/rtl8192ee/core/rtw_recv.c:4361:6: error: argument ‘RTW_TIMER_HDL_ARGS’ doesn’t match prototype
 void rtw_signal_stat_timer_hdl(RTW_TIMER_HDL_ARGS)
      ^
/root/rtl8192ee/core/rtw_recv.c:29:13: error: prototype declaration
 static void rtw_signal_stat_timer_hdl(void *ctx);
             ^
/root/rtl8192ee/core/rtw_recv.c:4367:34: error: ‘FunctionContext’ undeclared (first use in this function)
  _adapter *adapter = (_adapter *)FunctionContext;
                                  ^
/root/rtl8192ee/core/rtw_recv.c:4367:34: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:285: recipe for target '/root/rtl8192ee/core/rtw_recv.o' failed
make[2]: *** [/root/rtl8192ee/core/rtw_recv.o] Error 1
Makefile:1457: recipe for target '_module_/root/rtl8192ee' failed
make[1]: *** [_module_/root/rtl8192ee] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-184-generic'
Makefile:1816: recipe for target 'modules' failed
make: *** [modules] Error 2`

Checking further though I see that the driver is loaded:

> root@luffy:~/rtl8192ee# lsmod | grep rtl
rtl8192ee             102400  0
btcoexist              53248  1 rtl8192ee
rtl_pci                32768  1 rtl8192ee
rtlwifi                77824  2 rtl_pci,rtl8192ee
mac80211              741376  3 rtl_pci,rtlwifi,rtl8192ee
cfg80211              565248  2 mac80211,rtlwifi

but while trying to authenticate on my ESSID I cannot make my wireless connection work:

wlan0: CTRL-EVENT-DISCONNECTED bssid=44:fe:3b:db:b1:b6 reason=3 locally_generated=1
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="CentralPerk" auth_failures=1 duration=10 reason=CONN_FAILED
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD

I am using wpa_supplicant for my ESSID setup (WPA2-Personal auth). I have been reading around a lot but I couldn't find the solution yet. I also check the VT-d on BIOS to see if it is enabled and it is.

Could you please help me on this? Any idea how to overcome the issue and make the wireless card work would be much appreciated.

Thank in advance,
Stamatis

**Comment by lwfinger** [comment]
The driver that is loaded is the one built into the kernel. The one from this repo is 8192ee. If you were to use wicd or NetworkManager, it would probably work. Configuring wpa_supplicant is very difficult.

Your build errors are due to the fact that you have not refreshed the sources with a 'git pull'. I fixed those errors a long time ago! If you are not using git, then you should. Using the zip file from GitHub means a complete redownload the the entire source every time there is a change. With git, you only download the changes. Much more saving of network bandwidth.

**Comment by maritsas** [comment]
Thank you for your reply.
I am using git and I have the latest version of the repo.
The errors while trying to 'make' still persist though.

> root@luffy:~# git clone https://github.com/lwfinger/rtl8192ee.git
Cloning into 'rtl8192ee'...
remote: Enumerating objects: 626, done.
remote: Counting objects: 100% (626/626), done.
remote: Compressing objects: 100% (402/402), done.
remote: Total 626 (delta 228), reused 610 (delta 217), pack-reused 0
Receiving objects: 100% (626/626), 2.48 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (228/228), done.
Checking connectivity... done.

**Comment by lwfinger** [comment]
What kernel are you using? Your error is due to a change in kernel API for timers that changed in kernel 4.15.

**Comment by maritsas** [comment]
I am using kernel:

root@luffy:~# uname -mrs
Linux 4.4.0-184-generic x86_64

**Comment by lwfinger** [comment]
Then your problem is due to your distro backporting the change from kernel 4.15 to kernel 4.4. I do not handle that kind of change. You witt need to look at the source. In core/rtw_recv.c at line 4367, you will see a line that says:
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 15, 0)
That 15 will need to be changed to 4 in your case. Note, there will be lots of similar changes. You really should change to a newer kernel!
